### ISSUE TITLE
scrtobindiff.py: popen2 did not exist anymore in python3

### ISSUE THREAD

**Issue by dummys** [joxeankoret/pigaios#22]
-> $ ./srcbindiff.py -create
Traceback (most recent call last):
  File "./srcbindiff.py", line 7, in <module>
    import popen2
ModuleNotFoundError: No module named 'popen2'

**Comment by joxeankoret** [comment]
It doesn't support yet Python 3.

**Comment by dummys** [comment]
ok so why you didnt use as shebang: `#!/usr/bin/env python2` ?

**Comment by joxeankoret** [comment]
Because I've never considered it a problem and it doesn't support exclusively Linux but also *BSD and MacOSX. Let me search what is the truly multi-platform portable shebang if any...

**Comment by dummys** [comment]
Oh yeah, let me try to search for it too.

**Comment by joxeankoret** [comment]
Found it: https://blogs.gnome.org/mcatanzaro/2018/02/16/on-python-shebangs/

So, according to this and other articles, the one that works everywhere is "#!/usr/bin/env python2.7". Patching...

**Comment by dummys** [comment]
yes same information here: https://stackoverflow.com/questions/2429511/why-do-people-write-the-usr-bin-env-python-shebang-on-the-first-line-of-a-pyt

**Comment by joxeankoret** [comment]
1. The shebangs thing is fixed with 47e9940bdf58008d25c42f3d048fa66757f7fff3.
2. Regarding the PEP8 spaces thing: One ex-employer forced me to code using 2 spaces and I got used to it :) No other reason other than, maybe, that it's more readable to me.
3. Regarding the UTF-8 problem, glad it worked :+1:

**Comment by dummys** [comment]
2. You should send him this link: https://www.python.org/dev/peps/pep-0008/#indentation

**Comment by joxeankoret** [comment]
Extracted from [this link](https://developers.google.com/edu/python/introduction): "Fun fact: Google's internal style guideline dictates indenting by 2 spaces!"

**Comment by dummys** [comment]
quick question not related, where is the best way to contact you to have a rapid chat on diaphora ? tried twitter...

**Comment by psifertex** [comment]
Iirc, PEP also states using whatever currently exists is preferable so it's only ever an argument for when starting a new project, not updating an existing one.
