### ISSUE TITLE
using inline mode meet an error: ('Error:', 'table functions has no column named callees')

### ISSUE THREAD

**Issue by island255** [joxeankoret/pigaios#33]
When I try to execute srcbindiff.py -export by setting inline as 1, an error is printed: ('Error:', 'table functions has no column named callees').

As I look into the code, it may be caused by base_support.py at line 471:

    sql = """insert into functions(
               ea, name, prototype, prototype2, conditions,
               constants, constants_json, loops, switchs,
               switchs_json, calls, externals, filename,
               callees, source, recursive, indirect, globals,
               inlined, static, basename)
             select (select count(ea)+1 from functions),
               name || '_with_inlines', prototype, prototype2, conditions,
               constants, constants_json, loops, switchs,
               switchs_json, calls, externals, filename,
               callees, source, recursive, indirect, globals,
               inlined, static, basename
               from functions
              where id = ?"""

_callees_ doesn't exist in the table. And after I change it to _callees_json_, the problem was solved.

But I want to make sure that's the reason for this error and hope it can be corrected.

**Comment by joxeankoret** [comment]
The inlines support wasn't updated so, yes, that's the culprit. Thanks for reporting, I will fix it asap!
